---
title: "covid_Juanma"
author: "Juan Manuel Morales Joya"
date: "8/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## visualización Juanma

```{r}

library(dplyr)
library(ggplot2)
library(ggridges)
library(ggpubr)

covid_datos <- read.csv("Datasets/covid_datos.txt", sep=";", encoding = "UTF-8")

# Se genera una ultima columna al finalizar cada linea con ';' por lo que la eliminamos
covid_datos <- covid_datos[, 1:4]

# Para evitar problemas con los acentos en las columnas cambiamos el nombre de la primera
names(covid_datos)[1] <- "Fecha"

covid_datos$Fecha <- as.Date(covid_datos$Fecha, format='%d/%m/%Y')

indices <- which(is.na(covid_datos$Valor))
covid_datos$Valor[indices] = 0

```

```{r}

TCFeb <- covid_datos[(format(covid_datos$Fecha, "%m") == '02') & covid_datos$Territorio == "Andalucía" & covid_datos$Medida == "Total confirmados (PCR+test)", ]

TCFeb

TCMarzo <- covid_datos[(format(covid_datos$Fecha, "%m") == '03') & covid_datos$Territorio == "Andalucía" & covid_datos$Medida == "Total confirmados (PCR+test)", ]

TCMarzo

TCAbril <- covid_datos[(format(covid_datos$Fecha, "%m") == '04') & covid_datos$Territorio == "Andalucía" & covid_datos$Medida == "Total confirmados (PCR+test)", ]

TCAbril

gf <- ggplot(TCFeb, aes(x=Fecha, y=Valor)) +
  geom_point() +
  geom_line(aes(group = 1)) +
  labs(title = "Confirmados Febrero",
       y = "Confirmados",
       x = "Fecha")

gm <- ggplot(TCMarzo, aes(x=Fecha, y=Valor)) +
  geom_point() +
  geom_line(aes(group = 1)) +
  labs(title = "Confirmados Marzo",
       y = "Confirmados",
       x = "Fecha")

ga <- ggplot(TCAbril, aes(x=Fecha, y=Valor)) +
  geom_point() +
  geom_line(aes(group = 1)) +
  labs(title = "Confirmados Abril",
       y = "Confirmados",
       x = "Fecha")

figure2 <- ggarrange(gf,gm,ga)
annotate_figure(figure2, top = text_grob("Confirmados Feb, Mar, Abril", face = "bold", size = 12))

figure2



```

```{r}

# Números Totales Confirmados por Meses

sumF <- sum(TCFeb$Valor)

sumM <- sum(TCMarzo$Valor)

sumA <- sum(TCAbril$Valor)

vMeses <- c(Febrero = sumF, Marzo = sumM, Abril = sumA)

vMeses

barplot(vMeses)

```
